version: '3.8'

services:
  # API Gateway
  fb-analyzer-api-gateway:
    build:
      context: ./services/fb-analyzer-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/fb_analyzer
      - REDIS_URL=redis://redis:6379
    networks:
      - fb-analyzer-network

  # Auth Service
  fb-analyzer-auth-service:
    build:
      context: ./services/fb-analyzer-auth-service
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/fb_analyzer
      - REDIS_URL=redis://redis:6379
    networks:
      - fb-analyzer-network

  # Post Fetcher Service
  fb-analyzer-post-fetcher:
    build:
      context: ./services/fb-analyzer-post-fetcher
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/fb_analyzer
      - REDIS_URL=redis://redis:6379
      - FACEBOOK_API_KEY=${FACEBOOK_API_KEY}
    networks:
      - fb-analyzer-network

  # Post Analyzer Service
  fb-analyzer-post-analyzer:
    build:
      context: ./services/fb-analyzer-post-analyzer
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/fb_analyzer
      - REDIS_URL=redis://redis:6379
    networks:
      - fb-analyzer-network

  # Notification Service
  fb-analyzer-notification-service:
    build:
      context: ./services/fb-analyzer-notification-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - fb-analyzer-network

  # Data Processor (Golang Workers)
  fb-analyzer-data-processor:
    build:
      context: ./services/fb-analyzer-data-processor
    depends_on:
      - redis
      - mysql
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/fb_analyzer
      - REDIS_URL=redis://redis:6379
    networks:
      - fb-analyzer-network

  # Frontend
  fb-analyzer-frontend:
    build:
      context: ./services/fb-analyzer-frontend
    ports:
      - "3000:80"
    networks:
      - fb-analyzer-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=fb_analyzer
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./infrastructure/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fb-analyzer-network

  # Redis for Queue
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - fb-analyzer-network

  # Nginx for routing
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - fb-analyzer-api-gateway
      - fb-analyzer-frontend
    networks:
      - fb-analyzer-network

networks:
  fb-analyzer-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
